let Joi,APIError,getErrorResponse,getResponse,Users;_78f‍.x([["signin",()=>signin],["changePassword",()=>changePassword]]);_78f‍.w("joi",[["*",null,function(v){Joi=v}]]);_78f‍.w("../../services/APIError.js",[["default",["APIError"],function(v){APIError=v}]]);_78f‍.w("../mainModels.js",[["getErrorResponse",["getErrorResponse"],function(v){getErrorResponse=v}],["getResponse",["getResponse"],function(v){getResponse=v}]]);_78f‍.w("../../models/Users/index",[["default",["Users"],function(v){Users=v}]]);








       const signin = async (req, res, next) => {
    try {
        const phone = req.body.phone;

        const findUser = await Users.findOne({ phone });
        _78f‍.g.console.log(findUser)

        if(findUser && findUser.phone == phone){
            _78f‍.g.console.log(findUser)
          return res.send(getResponse(false, "User existed Please type another number"))
    
        }
    
        const data = req.body;
        const schema = Joi.object().keys({
            name: Joi.string().required(),
            phone: Joi.string().required(),
            email: Joi.string().required().email(),

            password: Joi.string().required().min(6).max(40),
            
            codeEmail: Joi.string().required(),
            codePhone: Joi.string().required()

        });

        const result = Joi.validate(data, schema);
        if (result.error) {
            return res.send(getResponse(false, result.error.details[0].message));
        }
        return next();
    }
    catch (e) {
        new APIError(e, 500, 'sign-in function in auth/validation.js');
        res.status(500).send(getErrorResponse());
    }

};

       const changePassword = async (req, res, next) => {
    try {
        const data = req.body;
        const schema = Joi.object().keys({
            email: Joi.string().required(),
            newPassword: Joi.string().required(),
            codePhone: Joi.string().required(),
            codeEmail: Joi.string().required()
        });

        const result = Joi.validate(data, schema);
        if (result.error) {
            return res.send(getResponse(false, result.error.details[0].message));
        }
        return next();
    }
    catch (e) {
        new APIError(e, 500, "login function in auth/validation")
        res.status(500).send(getErrorResponse());
    }
}

